using FairShare.API.OpenApi;

namespace FairShare.WebAPI.Extensions
{
    public static class OpenApiServiceExtensions
    {
        /// <summary>
        /// The OpenAPI document is generated by ASP.NET Core itself (/openapi/v1.json); Swagger UI
        /// in Program.cs only displays it. In Development the UI is at /swagger.
        /// </summary>
        public static IServiceCollection AddApiDocumentation(this IServiceCollection services)
        {
            services.AddOpenApi(options =>
            {
                options.AddDocumentTransformer((document, context, cancellationToken) =>
                {
                    document.Info.Title = "FairShare API";
                    document.Info.Version = "v1";
                    document.Info.Description =
                        "REST API за праћење личних трошкова, дијељење групних трошкова и поравнање дугова.";
                    return Task.CompletedTask;
                });

                options.AddDocumentTransformer<BearerSecuritySchemeTransformer>();
            });

            return services;
        }
    }
}
